ENV = bool(os.environ.get("ENV", False))
if ENV:
    TOKEN = os.environ.get("TOKEN")
    WORKERS = int(os.environ.get("WORKERS", 8))
    TMDBAPI = os.environ.get("TMDBAPI")
    DB_URI = os.environ.get("DATABASE_URL")
    GENIUS = os.environ.get("GENIUS")
    DEBUG = bool(os.environ.get("DEBUG", False))    
    APIID = os.environ.get("APIID")
    APIHASH = os.environ.get("APIHASH")
