    TOKEN = " "
    WORKERS = " "
    TMDBAPI = Config.TMDBAPI
    DB_URI = Config.DB_URI
    GENIUS = Config.GENIUS    
    DEBUG = Config.DEBUG    
    APP_URL = Config.APP_URL
    APIID = Config.APIID
    APIHASH = Config.APIHASH
