TOKEN = "bot token",
WORKERS = no of workers
TMDBAPI = IMDb Api
DB_URI = mangodb url
GENIUS = false
SPT_CLIENT_SECRET = Spotify secret id
SPT_CLIENT_ID = Spotify Id
DEBUG = false
ARLTOKEN = deezer token
APP_URL = app name
APIID = api id
APIHASH = api hash
